import type { CasePackage } from './caseRules.js';

/** Sample package catalog for demos/tests — real deployments supply this via feature config. */
export const samplePackageCatalog: CasePackage[] = [
  {
    id: 'mov-10',
    code: "MOV' 10",
    label: "MOV' 10",
    accent: 'graphite',
    description: 'Best for mild cases like crowding, spacing, or relapse.',
    maxAlignerSteps: 10,
    durationMonths: 12,
    refinements: 1,
    tsRevisions: 2,
    retainerSets: 1,
  },
  {
    id: 'eon-basic',
    code: 'EON_BASIC',
    label: 'EON_BASIC',
    accent: 'slate',
    description: 'Best for mild cases like crowding, spacing, or relapse.',
    maxAlignerSteps: 10,
    durationMonths: 'unlimited',
    refinements: 1,
    tsRevisions: 'unlimited',
    retainerSets: 'unlimited',
  },
  {
    id: 'mild-222',
    code: 'MILD222',
    label: 'MILD222',
    accent: 'navy',
    description: 'Best for mild cases like crowding, spacing, or relapse.',
    maxAlignerSteps: 10,
    durationMonths: 12,
    refinements: 'unlimited',
    tsRevisions: 'unlimited',
    retainerSets: 1,
  },
  {
    id: 'mild',
    code: 'MILD',
    label: 'MILD',
    accent: 'coral',
    description: 'Suitable for moderate to severe cases not requiring full unit A-P correction.',
    maxAlignerSteps: 30,
    durationMonths: 36,
    refinements: 1,
    tsRevisions: 'unlimited',
    retainerSets: 1,
  },
  {
    id: 'eon-plus',
    code: 'EON_PLUS',
    label: 'EON_PLUS',
    accent: 'emerald',
    description: 'Covers a wide range of mild to moderate cases.',
    maxAlignerSteps: 24,
    durationMonths: 'unlimited',
    refinements: 2,
    tsRevisions: 'unlimited',
    retainerSets: 'unlimited',
  },
  {
    id: 'eon-pro',
    code: 'EON_PRO',
    label: 'EON_PRO',
    accent: 'teal',
    description: 'Unlimited aligner steps for cases that need ongoing refinement.',
    maxAlignerSteps: 'unlimited',
    durationMonths: 36,
    refinements: 'unlimited',
    tsRevisions: 'unlimited',
    retainerSets: 2,
  },
  {
    id: 'mov-30',
    code: "MOV' 30",
    label: "MOV' 30",
    accent: 'mint',
    description: 'Suitable for moderate to severe cases not requiring full unit A-P correction.',
    maxAlignerSteps: 30,
    durationMonths: 36,
    refinements: 1,
    tsRevisions: 'unlimited',
    retainerSets: 1,
  },
  {
    id: 'mov-advanced',
    code: "MOV' Advanced",
    label: "MOV' Advanced",
    accent: 'plum',
    description: 'Ideal for advanced cases requiring extraction or A-P correction.',
    maxAlignerSteps: 'unlimited',
    durationMonths: 48,
    refinements: 'unlimited',
    tsRevisions: 'unlimited',
    retainerSets: 2,
  },
];
